version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 8000:3000
    volumes:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db